import type { Metadata } from 'next';
import 'css/globals.css';
import localFont from 'next/font/local';
import Providers from './Provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const mmFont = localFont({
  src: [
    {
      path: '../public/fonts/AcreMMVariable-Thin.ttf',
      weight: '100',
    },
    {
      path: '../public/fonts/AcreMMVariable-ExtraLight.ttf',
      weight: '200',
    },
    {
      path: '../public/fonts/AcreMMVariable-Light.ttf',
      weight: '300',
    },
    {
      path: '../public/fonts/AcreMMVariable-Regular.ttf',
      weight: '400',
    },
    {
      path: '../public/fonts/AcreMMVariable-DemiBold.ttf',
      weight: '500',
    },
    {
      path: '../public/fonts/AcreMMVariable-Demi.ttf',
      weight: '600',
    },
    {
      path: '../public/fonts/AcreMMVariable-Bold.ttf',
      weight: '700',
    },
    {
      path: '../public/fonts/AcreMMVariable-Black.ttf',
      weight: '800',
    },
  ],
  variable: '--font-acre',
});

const enFont = localFont({
  src: [
    {
      path: '../public/fonts/en.woff2',
      weight: '400',
    },
  ],
  variable: '--font-en',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${mmFont.variable} font-acre ${enFont.variable} font-en`}
      >
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
